name: Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test runner
        run: |
          echo "GitHub Runner works"
          uname -a
          python3 --version
