name: Test GitHub to MinIO

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Runner info
        run: |
          echo "Public IPv4:"
          curl -4 -s https://api.ipify.org
          echo
          echo "Azure region:"
          echo "$RUNNER_ENVIRONMENT"

      - name: Test 443
        run: |
          echo "===== HTTPS 443 ====="
          for i in 1 2 3 4 5 6 7 8 9 10; do
            curl -4 -sS \
              -o /dev/null \
              --connect-timeout 10 \
              -w "443  connect=%{time_connect}s tls=%{time_appconnect}s start=%{time_starttransfer}s total=%{time_total}s\n" \
              https://s3.002259.xyz/
          done

      - name: Test 8443
        run: |
          echo "===== HTTPS 8443 ====="
          for i in 1 2 3 4 5 6 7 8 9 10; do
            curl -4 -sS \
              -o /dev/null \
              --connect-timeout 10 \
              -w "8443 connect=%{time_connect}s tls=%{time_appconnect}s start=%{time_starttransfer}s total=%{time_total}s\n" \
              https://s3.002259.xyz:8443/
          done
